### ISSUE TITLE
Job fails when running pbsmrtpipe.pipelines.sa3_ds_ccs_align

### ISSUE THREAD

**Issue by lennythomas** [PacificBiosciences/pbsmrtpipe#110]
When I run pbsmrtpipe.pipelines.sa3_ds_ccs_align the job fails right away when it calls `task_pbccs_ccs --resolved-tool-contract  /data/tasks/pbccs.tasks.ccs-0/resolved-tool-contract.json`. From what I can tell there is no `task_pbccs_ccs` exe with pbsmrtpipe. Where are all the executables like ccs, quiver, blasr, etc? Or do I need to install separate packages too? I tried installing pbccs, but running into an issue there too (see https://github.com/PacificBiosciences/pbccs/issues/72). Any pointers you can provide would be great.

**Comment by mpkocher** [comment]
pbsmrtpipe is a tool in the SMRT Analysis Tool Suite and only ships with the executables listed in the setup.py (which depend on pbcommand and pbcore). pbsmrtpipe doesn't contain executables, such as quiver or blasr. I'll the update the README.md hopefully clarify this. 

We're currently in the progress of migrating from perforce to github and not all the tools have made the transition yet.

```
pbsmrtpipe_test)pbsmrtpipe $> pbsmrtpipe show-template-details pbsmrtpipe.pipelines.sa3_ds_ccs_align
Registry Loaded. Number of ToolContracts:103 FileTypes:43 ChunkOperators:13 Pipelines:35
Pipeline id   : pbsmrtpipe.pipelines.sa3_ds_ccs_align
Pipeline name : SA3 Consensus Read Mapping
Description   : 
    ConsensusRead (CCS) + Mapping pipeline, starting from subreads.
    
Tags          : mapping 
Entry points  : 2
********************
$entry:eid_subread
$entry:eid_ref_dataset

Bindings      : 7
********************
    pbalign.tasks.pbalign_ccs:0 -> pbreports.tasks.mapping_stats_ccs:0
              pbccs.tasks.ccs:0 -> pbsmrtpipe.tasks.bam2fasta_ccs:0
              pbccs.tasks.ccs:0 -> pbreports.tasks.ccs_report:0
              pbccs.tasks.ccs:0 -> pbsmrtpipe.tasks.bam2fastq_ccs:0
              pbccs.tasks.ccs:0 -> pbalign.tasks.pbalign_ccs:0
         $entry:eid_ref_dataset -> pbalign.tasks.pbalign_ccs:1
             $entry:eid_subread -> pbccs.tasks.ccs:0
No default task options
```

For the CCS based pipeline of interest, there's several tasks that requires tools that are not included in pbsmrtpipe. The naming schema is {tool-namespace}.tasks.{task-id}. The tool namespace is approximately the name of the github repo.  

Unfortunately, the version of pbalign  is not up to date with the internal perforce version and the pbreports python package has not been migrated to github yet.

My suggestion would be to wait for till the next iteration of SMRT Analysis Suite which will have all the required tools to run the pipeline.

**Comment by lennythomas** [comment]
Thanks. Just to confirm though I would still have to install both pbsmrtpipe and smrtanalysis or are you saying the next version of smrtanalysis would have everything?

**Comment by mpkocher** [comment]
The next release of SMRT Analysis Suite will have all the required tools (including pbsmrtpipe, pbccs) for all the registered pipelines displayed using the 'pbsmrtpipe show-templates' command.

**Comment by lennythomas** [comment]
Awesome. What is the expected launch date for the new version?

**Comment by mpkocher** [comment]
There's a beta of an (internal) build system that might be useful to build the SA3 tools.

https://github.com/PacificBiosciences/pitchfork

`make reseq-core pblaa` should get you the tools necessary to run the core pipelines
