### ISSUE TITLE
Invalid In-degree (0)

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pbsmrtpipe#21]
What am I doing wrong? I've just add a 2-input/1-output task, and I get this ERROR message:
```
[ERROR] 2015-08-21 16:50:06,025 Invalid In-degree (0) of task id TaskBindingNode falcon_ns.tasks.task_falcon_build_rdb-0 with file node BindingInFileNode fa
lcon_ns.tasks.task_falcon_build_rdb-0 PacBio.FileTypes.generic_fofn-0.1.
```

Here is my pipeline:
```python
@dev_register("pipe_falcon", "Falcon Pipeline", tags=("local", ))
def get_task_falcon_local_pipeline():
    """Simple example pipeline"""
    return [
            ('$entry:e_01', 'falcon_ns.tasks.task_falcon_hello_world:0'),
            ('$entry:e_01', 'falcon_ns.tasks.task_falcon_config:0'),
            ('falcon_ns.tasks.task_falcon_config:0', 'falcon_ns.tasks.task_falcon_make_fofn_abs:0'),
            ('falcon_ns.tasks.task_falcon_config:0',        'falcon_ns.tasks.task_falcon_build_rdb:0'),
            ('falcon_ns.tasks.task_falcon_make_fofn_abs:0', 'falcon_ns.tasks.task_falcon_build_rdb:0'),
            ]
```
The bottom two bindings are new. Here is the task:
```python
@registry('task_falcon_build_rdb', '0.0.0', [FC_JSON, FC_FOFN], [FC_BASH], is_distributed=False)
def run_rtc(rtc):
    return run_falcon_build_rdb(rtc.task.input_files, rtc.task.output_files)
```

**Comment by mpkocher** [comment]
You can't bind two outputs to the same input. 

falcon_ns.tasks.task_falcon_build_rdb
```
('falcon_ns.tasks.task_falcon_config:0',        'falcon_ns.tasks.task_falcon_build_rdb:0'),
('falcon_ns.tasks.task_falcon_make_fofn_abs:0', 'falcon_ns.tasks.task_falcon_build_rdb:0')
```

Needs to be (or a different input index of task_falcon_build_rdb task ).

```
('falcon_ns.tasks.task_falcon_config:0',        'falcon_ns.tasks.task_falcon_build_rdb:0'),
('falcon_ns.tasks.task_falcon_make_fofn_abs:0', 'falcon_ns.tasks.task_falcon_build_rdb:1')
```

**Comment by pb-cdunn** [comment]
Ok. Now I see. The restriction is actually much deeper than what you mentioned before: >= 1 output. You're actually binding file to task to file

A similar restriction has been one of my long-standing complaints about **make**, but it's always hard to explain the use-case.

* https://www.gnu.org/software/make/manual/html_node/Multiple-Targets.html

**make** expects to run *once for each target*, which is wrong for a tool with multiple outputs, e.g. **swig**. It's what caused me to switch to **scons** 15 years ago. (And I will never switch back to **scons**, which has far worse problems.)

In the case of pbsmrtpipe, the task is run only once, right? That is at least an improvement. I just need pseudo-targets, yes? Fine. At least now I understand the seemingly arbitrary restriction in #16. It's simply a result of the graph you've chosen. Ok.

**Comment by pb-cdunn** [comment]
Do you see comments on a closed issue? I'm not sure.
