### ISSUE TITLE
no-failure mode for pbtestkit-runner

### ISSUE THREAD

**Issue by natechols** [PacificBiosciences/pbsmrtpipe#223]
For our Jenkins tests, it would be useful if we could have a "--no-failure" flag or similar that tells the program to always exit 0 if pbsmrtpipe runs successfully, even if tests fail.  Jenkins will still show the test failures but the build will be yellow, not red.  Right now we are doing things like this in Jenkins:

pbtestkit-runner tests.txt || echo "some tests failed"

but this also suppresses real problems like a test module not being loaded, which really should show up as a build failure.

(This is an easy fix, I think, so I'm happy to do it myself if it's acceptable.)

**Comment by mpkocher** [comment]
Would adding `set +e` to jenkins.sh solve this problem?

**Comment by natechols** [comment]
No, because that won't distinguish between the program running but failing tests, versus some kind of logic error such as test modules not loading, or the program simply not being available.

**Comment by mpkocher** [comment]
Would you mind adding a `--ignore-test-results` to runner.py and multirunner.py which will only return the pbsmrtpipe exit code and ignore any test result(s).

I would encourage considering to migrate `pysiv.custom.base` the use a model similar to `pbsmrtpipe.testkit.base`.

At the testkit level, there's a very conscious choice to never use  `setupClass`. Legacy code prior to pysiv1 used this often an it was very difficult to debug. 

I made an explicit design choice in pysiv1 to do the dynamic constructing of test class(es) using the `monkey_patch` deco model *before* nose runner is every involved (which will run setupClass). In testkit/pysiv2, the model has been simplified; func that does work, wrapped in a closure of `self`, then bolt that on to test case. The `monkey_patch` is just a function over `cls` so it extensible/composable.

https://github.com/PacificBiosciences/pbsmrtpipe/blob/master/pbsmrtpipe/testkit/base.py

If you have a bogus test that you're trying to load, or if there's a bug in base.py,  pbtestkit-runner will immediately fail. 

Here's an example of trying to load a test that doesn't exist.

```
[pbsmrtpipe:pipeline]

id = dev_01
description = Dev example
author = mkocher

# debug mode
debug = True

pipeline_xml = workflow_id.xml
preset_xml = preset.xml

[entry_points]
e_01 = input.txt


[tests]
# TACOS
pbsmrtpipe.testkit.core = test_tacos
```

Now running

```
(gh_mk_pbsmrtpipe_test)dev_01 $> pbtestkit-runner --debug testkit.cfg 
Using pbcommand v0.3.0
No module named test_tacos
Traceback (most recent call last):
  File "/Users/mkocher/.virtualenvs/gh_mk_pbsmrtpipe_test/lib/python2.7/site-packages/pbcommand/cli/core.py", line 79, in _pacbio_main_runner
    return_code = func(*args, **kwargs)
  File "/Users/mkocher/.virtualenvs/gh_mk_pbsmrtpipe_test/lib/python2.7/site-packages/pbsmrtpipe/testkit/runner.py", line 178, in _args_run_butler
    test_cases = L.parse_cfg_file(args.testkit_cfg)
  File "/Users/mkocher/.virtualenvs/gh_mk_pbsmrtpipe_test/lib/python2.7/site-packages/pbsmrtpipe/testkit/loader.py", line 85, in parse_cfg_file
    m = importlib.import_module(module_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named test_tacos
Traceback (most recent call last):
  File "/Users/mkocher/.virtualenvs/gh_mk_pbsmrtpipe_test/lib/python2.7/site-packages/pbcommand/cli/core.py", line 79, in _pacbio_main_runner
    return_code = func(*args, **kwargs)
  File "/Users/mkocher/.virtualenvs/gh_mk_pbsmrtpipe_test/lib/python2.7/site-packages/pbsmrtpipe/testkit/runner.py", line 178, in _args_run_butler
    test_cases = L.parse_cfg_file(args.testkit_cfg)
  File "/Users/mkocher/.virtualenvs/gh_mk_pbsmrtpipe_test/lib/python2.7/site-packages/pbsmrtpipe/testkit/loader.py", line 85, in parse_cfg_file
    m = importlib.import_module(module_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named test_tacos
exiting with return code 2 in 0.00 sec.
```

if the monkey patching is successful, any test method that fails, will just be a test method that fails. It's not going to be potentially hidden by the nose runner machinery.

**Comment by natechols** [comment]
"""If you have a bogus test that you're trying to load, or if there's a bug in base.py, pbtestkit-runner will immediately fail."""

Right, this is what I want - right now we are (inadvertently) suppressing those errors in Jenkins.

**Comment by mpkocher** [comment]
There's two code paths. Errors that are caught by the loader or metaprogramming will immediately fail, whereas any failures raised by `setupClass` will be handled under the nose runner and might not yield the expected results. Currently, nose is adding a new failed test case at the class level and marking tests in the Xunit output as successful (this might be a bug translating the raw results).

https://gist.github.com/mpkocher/de922715a1f4d2932433

Then add `pbsmrtpipe.testkit.core = test_tacos` to testkit.ctg.

I believe the only reason the error shows up in the Xunit is due to this.

(This looks like it was original added by Marcus)
https://github.com/PacificBiosciences/pbsmrtpipe/blob/master/pbsmrtpipe/testkit/xunit.py#L245

While there will be a new test class error, `<testcase classname="pbsmrtpipe.testkit.core.test_tacos.TestTacos" name="TestTacos" time="1.000">` with the expected division by zero exception,  the original test will look like it succeeded. 
` <testcase classname="pbsmrtpipe.testkit.core.test_tacos.TestTacos.test_custom_tacos" name="test_custom_tacos" time="1.000" />`
