### ISSUE TITLE
pbsmrtpipe hangs when max_total_nproc < max_nproc and chunk_mode ="False"

### ISSUE THREAD

**Issue by ben-lerch** [PacificBiosciences/pbsmrtpipe#234]
I would like to suggest that a modification be made to pbsmrtpipe so that it throws an error message, rather than hanging, when max_total_nproc < max_nproc and chunk_mode ="False". I discovered that resequencing on pbsmrtpipe hangs after reporting “successfully validated binding graph”, but when I set chunk_mode to “True”, then it no longer hanged.

Here were the relevant parameter settings when pbsmrtpipe hanged:
chunk_mode ="False"
max_total_nproc=10
max_nproc=16
max_nchunks=48
max_nworkers=768

And when it didn't hang:
chunk_mode ="True"
max_total_nproc=10
max_nproc=16
max_nchunks=48
max_nworkers=768

**Comment by mpkocher** [comment]
I believe this has been fixed for quite some time now.
