### ISSUE TITLE
replace static test files with automatically generated inputs

### ISSUE THREAD

**Issue by natechols** [PacificBiosciences/pbsmrtpipe#240]
Especially here:

https://github.com/PacificBiosciences/pbsmrtpipe/blob/master/pbsmrtpipe/tests/test_tools_dev_tasks.py

where we have very poor coverage on CircleCI because they require static data that we have locally.  Where possible these should be replaced by random files generated on the fly.  Doing this for BAM data will require some additional infrastructure in pbcore.

(I'll deal with this, but filing it here so I/we don't forget.)

**Comment by mpkocher** [comment]
Sounds good. If you want to put some code in a new subpackage within pbsmrtpipe that would be fine with me. I suspect you and Martin will eventually migrate these mock test tools into the forthcoming pbcoretools package.

**Comment by mpkocher** [comment]
Please feel free to pull from mock.py as well.

https://github.com/PacificBiosciences/pbsmrtpipe/blob/master/pbsmrtpipe/mock.py

**Comment by natechols** [comment]
All of the tests dependent on BAM data (etc.) have been relocated anyway, and we are now using the PacBioTestData repo for static input files.
