### ISSUE TITLE
Build/Install Broken

### ISSUE THREAD

**Issue by evolvedmicrobe** [PacificBiosciences/pbsmrtpipe#402]
git clone followed by make install won't work.  The requirements file specifies pbcore >= 1.2.10, however a version this high isn't even available on PyPi (https://pypi.python.org/simple/pbcore/)

**Comment by mpkocher** [comment]
With the transition from perforce to github, there are still are some items that we're sorting out. 

During out development cycle each project is pushing to master and we want other tools and package to immediately leverage those fix and changes. Given that the code is still in still changing pretty rapidly (depending on the package), it's not really practice to push to pypi on every version change. 

I believe the current model from the pacbio python packages is create a release on github and to push to pypi with each official release of SA (there's nothing that precludes an author from pushing to recent bug fixes to pypi). I'll try to communicate this to other developers and solicit feedback.

I've filed a new issue to pbcore and pbcommand to cut a new release compatible with 3.1.0 and push to pypi to address your original issue.

https://github.com/PacificBiosciences/pbcommand/issues/123

https://github.com/PacificBiosciences/pbcore/issues/94

https://github.com/PacificBiosciences/pbsmrtpipe/issues/403

In the meantime, I would suggest installing from master using this requirements.txt file.

`pip install -r PB_REQUIREMENTS.txt`

and then

`pip install .`

Let me know if this resolved your build issues.

**Comment by mpkocher** [comment]
Here's an example:

https://gist.github.com/mpkocher/0398f926b9f0d500ecb6a9dcb442bb44

Note, if you want to run the tests, you'll need to run `pip install -r REQUIREMENTS_DEV.txt`

**Comment by dalexander** [comment]
pbcore 1.2.10 on pypi now
