### ISSUE TITLE
test-sanity fails

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pbsmrtpipe#45]
Can someone google-hangout with me? That was very effective with Nat last week. I can make time this weekend if I know a time in advance. I will be available after 2PM PT today.

I am not actually working on the Gathering right now, but I want test-sanity to pass so that I can be confident that I might get this all working on time for Tuesday. From `make test-sanity`:
```python
pbsmrtpipe.exceptions.MalformedChunkOperatorError: Operator pbsmrtpipe.operators.chunk_task_falcon_run_daligner_jobs malformed. task falcon_ns.tasks.task_falcon_run_daligner_jobs input 1 is not bound in Gather chunks [('falcon_ns.tasks.task_falcon_run_daligner_jobs', 0)]
ChunkOperator(idx='pbsmrtpipe.operators.chunk_task_falcon_run_daligner_jobs', scatter=<Scatter falcon_ns.tasks.task_falcon_run_daligner_jobs pbsmrtpipe.tasks.scatter_run_daligner_jobs > , gather=Gather(chunks=[GatherChunk(gather_task_id='pbsmrtpipe.tasks.gather_run_daligner_jobs', chunk_key='$chunk.filtered_fasta_id', task_input='falcon_ns.tasks.task_falcon_run_daligner_jobs:0')]))
```

Binding for the allegedly unbound task:
```json
          ('falcon_ns.tasks.task_falcon_config:0', 'falcon_ns.tasks.task_falcon_run_daligner_jobs:0'),
          ('falcon_ns.tasks.task_falcon_build_rdb:0', 'falcon_ns.tasks.task_falcon_run_daligner_jobs:1'),
```

Chunk operator xml:
```xml
<chunk-operator id="pbsmrtpipe.operators.chunk_task_falcon_run_daligner_jobs">

    <task-id>falcon_ns.tasks.task_falcon_run_daligner_jobs</task-id>

    <scatter>
        <scatter-task-id>pbsmrtpipe.tasks.scatter_run_daligner_jobs</scatter-task-id>
        <chunks>
            <chunk out="$chunk.fasta_id" in="falcon_ns.tasks.task_falcon_run_daligner_jobs:0"/>
        </chunks>
    </scatter>
    <!-- Define the Gather Mechanism -->
    <gather>
        <chunks>
            <chunk>
                <!-- This is actually a txt -->
                <gather-task-id>pbsmrtpipe.tasks.gather_run_daligner_jobs</gather-task-id>
                <chunk-key>$chunk.filtered_fasta_id</chunk-key>
                <task-output>falcon_ns.tasks.task_falcon_run_daligner_jobs:0</task-output>
            </chunk>
        </chunks>
    </gather>
</chunk-operator>
```
Gathering contract parser:
```python
TOOL_ID = "pbsmrtpipe.tasks.gather_run_daligner_jobs"
CHUNK_KEY = "$chunk.daligner_job_id"

def get_contract_parser():
    driver = "python -m pbsmrtpipe.tools_dev.gather_run_daligner_jobs --resolved-tool-contract "

    p = get_gather_pbparser(TOOL_ID, "0.1.3", "Gather Daligner",
                            "Gather Daligner Jobs", driver, is_distributed=False)

    p.add_input_file_type(FileTypes.CHUNK, "cjson_in", "Gather ChunkJson",
                          "Fasta Gather Chunk JSON")

    p.add_output_file_type(FileTypes.FOFN, "fofn", "FOFN LAS maybe?",
                           "FOFN Not Sure Yet",
                           "file_gathered.fofn")
    p.add_output_file_type(FileTypes.TXT, "job_done", "JobDone",
                           "Job Done",
                           "file_gathered.txt")

    # FIXME. There's an a bit of friction between the TC and the argrunning
    # layer here. For nproc and nchunks, chunk-key, the values are a bit
    # different between the two backends.
    p.arg_parser.add_str("pbsmrtpipe.task_options.task_falcon_run_daligner_job_scatter_chunk_key", "chunk_key",
                         "$chunk.daligner_job_id", "Chunk key", "Chunk key to use (format $chunk:{chunk-key}")
    return p
```

**Comment by natechols** [comment]
I have some time free this afternoon after around 3pm or so if you want to
talk.  However: your gather tool contract defines two different outputs,
but the chunk operator only indicates a single output to be gathered.  I
doubt this will work as intended.  (If you make sure everything is pushed
to your github fork I can take a closer look later.)

**Comment by pb-cdunn** [comment]
3pm PT is fine. The 'fal' branch is up-to-date.

I added the 2nd output in an attempt to address the problem.

I could have reverted to the point where things were working, but today I squashed most of the commits. (Repeatedly rebasing onto the tip of master became very slow, and I didn't have time to track down why.) But I'll try to find a working commit anyway...

**Comment by pb-cdunn** [comment]
@natechols explains the problem to me. Thanks!

(Using only 1 output on gatherable tasks seems to be a good idea. Otherwise, I guess I would need extra gatherers.)

**Comment by natechols** [comment]
We were able to resolve this, but I think there is a typo in the error message (models.py:L662) - shouldn't it be "output 1 is not bound"?

**Comment by natechols** [comment]
On Sat, Sep 5, 2015 at 4:05 PM, Christopher Dunn <notifications@github.com>
wrote:

> (Using only 1 output on gatherable tasks seems to be a good idea.
> Otherwise, I guess I would need extra gatherers.)
>

This isn't actually that big a deal - I have a task that has five outputs,
three of them in the same format.  (Fortunately, the gather task can be
used multiple times in a single chunk operator.)  But it is definitely
better not to define more outputs than you actually need in the tool
contracts.
