### ISSUE TITLE
unanimity/include/pacbio/data/internal/ConversionFunctions.h:132:1: error: expression ‘<throw-expression>’ is not a constant-expression

### ISSUE THREAD

**Issue by bensonlew** [PacificBiosciences/pbsmrtpipe#597]
when I install  unanimity
[ 68%] Building CXX object src/CMakeFiles/cc2.dir/models/MarginalModelForm.cpp.o
In file included from /mnt/ilustre/users/bingxu.liu/bio-soft/unanimity/include/pacbio/data/internal/BaseEncoding.h:45:0,
                 from /mnt/ilustre/users/bingxu.liu/bio-soft/unanimity/include/pacbio/consensus/ModelConfig.h:49,
                 from /mnt/ilustre/users/bingxu.liu/bio-soft/unanimity/src/models/MarginalModelForm.cpp:44:
/mnt/ilustre/users/bingxu.liu/bio-soft/unanimity/include/pacbio/data/internal/ConversionFunctions.h: In function ‘constexpr uint8_t PacBio::Data::detail::{anonymous}::ASCIIToNCBI4naImpl(char, bool)’:
/mnt/ilustre/users/bingxu.liu/bio-soft/unanimity/include/pacbio/data/internal/ConversionFunctions.h:132:1: error: expression ‘<throw-expression>’ is not a constant-expression
 }
 ^
/mnt/ilustre/users/bingxu.liu/bio-soft/unanimity/include/pacbio/data/internal/ConversionFunctions.h: In function ‘constexpr uint8_t PacBio::Data::detail::{anonymous}::NCBI4naToNCBI2naImpl(uint8_t)’:
/mnt/ilustre/users/bingxu.liu/bio-soft/unanimity/include/pacbio/data/internal/ConversionFunctions.h:175:1: error: expression ‘<throw-expression>’ is not a constant-expression
 }
 ^
In file included from /mnt/ilustre/users/bingxu.liu/bio-soft/unanimity/include/pacbio/consensus/ModelConfig.h:49:0,
                 from /mnt/ilustre/users/bingxu.liu/bio-soft/unanimity/src/models/MarginalModelForm.cpp:44:
/mnt/ilustre/users/bingxu.liu/bio-soft/unanimity/include/pacbio/data/internal/BaseEncoding.h: At global scope:
/mnt/ilustre/users/bingxu.liu/bio-soft/unanimity/include/pacbio/data/internal/BaseEncoding.h:119:31: error: explicitly defaulted function ‘constexpr PacBio::Data::detail::NCBI2na& PacBio::Data::detail::NCBI2na::operator=(const PacBio::Data::detail::NCBI2na&)’ cannot be declared as constexpr because the implicit declaration is not constexpr:
     inline constexpr NCBI2na& operator=(const NCBI2na&) = default;
                               ^
/mnt/ilustre/users/bingxu.liu/bio-soft/unanimity/include/pacbio/data/internal/BaseEncoding.h:120:31: error: explicitly defaulted function ‘constexpr PacBio::Data::detail::NCBI2na& PacBio::Data::detail::NCBI2na::operator=(PacBio::Data::detail::NCBI2na&&)’ cannot be declared as constexpr because the implicit declaration is not constexpr:
     inline constexpr NCBI2na& operator=(NCBI2na&&) = default;
                               ^
/mnt/ilustre/users/bingxu.liu/bio-soft/unanimity/include/pacbio/data/internal/BaseEncoding.h:159:31: error: explicitly defaulted function ‘constexpr PacBio::Data::detail::NCBI4na& PacBio::Data::detail::NCBI4na::operator=(const PacBio::Data::detail::NCBI4na&)’ cannot be declared as constexpr because the implicit declaration is not constexpr:
     inline constexpr NCBI4na& operator=(const NCBI4na&) = default;
                               ^
/mnt/ilustre/users/bingxu.liu/bio-soft/unanimity/include/pacbio/data/internal/BaseEncoding.h:160:31: error: explicitly defaulted function ‘constexpr PacBio::Data::detail::NCBI4na& PacBio::Data::detail::NCBI4na::operator=(PacBio::Data::detail::NCBI4na&&)’ cannot be declared as constexpr because the implicit declaration is not constexpr:
     inline constexpr NCBI4na& operator=(NCBI4na&&) = default;

**Comment by armintoepfer** [comment]
This is not a pbsmrtpipe issue. Update your compiler and try again. If you still encounter problems, download the latest SMRT Link distribution from pacb.com or contact official PacBio support.
