### ISSUE TITLE
Unsupported sequencing chemistry

### ISSUE THREAD

**Issue by byustudent** [PacificBiosciences/pbsmrtpipe#599]
I've seen this problem before on this website, but I didn't quite understand the nature of the solution. 
I am trying to run the ccs command with my files and it says 
** 20171229 21:27:45.094 -|- FATAL      -|- Runner -|- 0x2add8c170b80|| -|- unsupported sequencing chemistry combination:
    binding kit:        100-862-200
    sequencing kit:     101-309-500
    basecaller version: 5.0.0.6236

**

From what I understand, this is caused by a recent sequencing chemistry that hasn't been updated yet in this program. 
How would you suggest going about this?

**Comment by evolvedmicrobe** [comment]
See the discussion at: https://github.com/PacificBiosciences/pbsmrtpipe/issues/596 for some work arounds.

**Comment by cschin** [comment]
if you like to compile it under ubuntu, here are set of packages you need (tested on 16.04) to compile unanimity with @evolvedmicrobe's script in #596 
```
apt-get install -qqy cmake zlib1g zlib1g-dev libboost-all-dev libbz2-dev liblzma-dev pkg-config libevent-pthreads-2.0-5 doxygen software-properties-common python-software-properties git
add-apt-repository -y  ppa:ubuntu-toolchain-r/test
apt-get update && apt-get install -y gcc-6 g++-6
cd /usr/bin && ln -sf gcc-6 gcc && ln -sf g++-6 g++
```

**Comment by armintoepfer** [comment]
Please contact PacBio tech support for further help.
