### ISSUE TITLE
Stop using DropBox for testdata

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pbsmrtpipe#6]
See #4.

A smaller model would be great. For now, the real problem is that this pulls several MB from my personal DropBox account on every build. Eventually, DropBox will complain.

Other ideas:
* Store testdata in S3. (Only git-sym.makefile needs to change.)
* Store the testdata in the Docker image.
* Use a GitHub repo strictly for test-data.

We also need to think about how/when data is needed within PacBio builds. git-sym is ext/pi, but nothing uses it today.

We need to address this within a week or two. DropBox will begin to make the download unavailable for ever-increasing durations.

**Comment by mpkocher** [comment]
Test data is generated within the jobs, or use sentinel-ish (txt) files to generate files (e.g., fasta)

**Comment by pb-cdunn** [comment]
> We need to address this within a week or two. - August 2015
