### ISSUE TITLE
convert subreads fastq to subreads bam

### ISSUE THREAD

**Issue by gemygk** [PacificBiosciences/pbsmrtpipe#600]
Hi,

Could you please suggest the best way to convert a subreads.fastq to subreads.bam file, i.e, that keeps all the required header ["HD"]["pb"] information as well as the BAM attributes for the downstream PacBio secondary analysis pipelines.

The fastq file I have downloaded from PacBio Datasets website are from below link
https://github.com/PacificBiosciences/DevNet/wiki/H_sapiens_54x_release

My intention is to provide the subreads.subreadset.xml (using command 'dataset create --type SubreadSet') as input for the pbsmrtpipe HGAP pipeline (using SMRTLINK v5.1.0).

I have tried Picard FastqToSam - https://broadinstitute.github.io/picard/command-line-overview.html#FastqToSam, but it was not that helpful in creating a PacBio specific BAM format.

Any help is much appreciated.

Best,
Gemy

**Comment by shenweima** [comment]
I have the same question....

**Comment by jiawen2077** [comment]
I have the same question too.

**Comment by KatharinaHoff** [comment]
I have the same question too.

**Comment by armintoepfer** [comment]
You can't.
