### ISSUE TITLE
task options not propagated to preset.xml

### ISSUE THREAD

**Issue by natechols** [PacificBiosciences/pbsmrtpipe#68]
If I run this:

 pbsmrtpipe show-template-details pbsmrtpipe.pipelines.sa3_ds_isoseq

at the end, it shows:

Default Task Options
'pbccs.task_options.min_passes' -> 1

but if I run it with "-o preset.xml", the output XML has the global default value (3) for min_passes.

**Comment by mpkocher** [comment]
I believe this is working as expected now.
