### ISSUE TITLE
can't get all options at once in preset.xml

### ISSUE THREAD

**Issue by natechols** [PacificBiosciences/pbsmrtpipe#82]
I can do this to get workflow-specific options:

pbsmrtpipe show-template-details pbsmrtpipe.pipelines.sa3_ds_resequencing -o preset_tasks.xml

or this to get the "global" options:

pbsmrtpipe show-workflow-options -o preset.xml

but if I want both I have to copy-and-paste XML.  Is there a way to get all options at once, or can we specify multiple presets when running a pipeline?

**Comment by mpkocher** [comment]
Multiple --preset-xml support has been added. Can you test this out?

**Comment by mpkocher** [comment]
@natechols Any feedback?

**Comment by natechols** [comment]
Two problems, for which I have a fix:

1. Just a usage issue: this isn't the most intuitive syntax:

pbsmrtpipe pipeline-id whatever --preset-xml FILE1 FILE2 ...

I'm more accustomed to:

pbsmrtpipe pipeline-id whatever --preset-xml FILE1 --preset-xml FILE2

2. It's populating the workflow options for each file with default values for any option not included in the file, so if I have two files, the first with workflow options, the second with task options, the options from the first file will be overwritten with the defaults for the second.
