### ISSUE TITLE
error building docs

### ISSUE THREAD

**Issue by natechols** [PacificBiosciences/pbsmrtpipe#92]
When I run "make doc" I get a lot of errors like this:

/home/nechols/src/pbsmrtpipe/docs/pbsmrtpipe.rst:29: WARNING: autodoc: failed to import module u'pbsmrtpipe.cli'; the following exception was raised:
Traceback (most recent call last):
  File "/home/nechols/py/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/nechols/py/local/lib/python2.7/site-packages/pbsmrtpipe-0.32.1-py2.7.egg/pbsmrtpipe/cli.py", line 10, in <module>
    from pbsmrtpipe.cli_utils import main_runner, args_executer, validate_file
  File "/home/nechols/py/local/lib/python2.7/site-packages/pbsmrtpipe-0.32.1-py2.7.egg/pbsmrtpipe/cli_utils.py", line 9, in <module>
    from pbcore.util.Process import backticks
RuntimeError: sys.path must be a list of directory names

with the exact point of breakage varying from module to module, but always an import statement. Google turned up several other reports of this error message, none of which gave me any better of an idea what is broken or how to fix it.

**Comment by mpkocher** [comment]
It's probably the recent changes to the conf.py to try to get RTD to work. 

https://github.com/PacificBiosciences/pbsmrtpipe/blob/master/docs/conf.py#L15

I don't really have time to debug this right now. Any help on getting that working would be appreciated.

**Comment by natechols** [comment]
Can you please try updating RTD now?  (Or give me access to do it myself.)

**Comment by mpkocher** [comment]
I've updated the post hook in github. Should be automatically triggered now. 

But it's still failing :(

https://readthedocs.org/projects/pbsmrtpipe/builds/

**Comment by natechols** [comment]
I should have looked closer at the log, there's no way my "fix" would deal with this.  Is there a way to install h5py without having to compile it?

**Comment by mpkocher** [comment]
I tried a few things and couldn't get it to work. 

This might help:

https://github.com/rtfd/readthedocs.org/issues/766

At this point it might be easier to go with the gh-pages route.

**Comment by natechols** [comment]
If you have control over the build commands that RTD uses, can you cheat and remove pbcore from REQUIREMENTS.txt?  The conf.py changes are complementary to this, but we need to get it to stop building h5py.

**Comment by mpkocher** [comment]
I've setup the package, setup.py always loads REQUIREMENTS.txt. 

I am not really thrilled about this, but you could filter pbcore out the requirements list loaded by the function in setup.py if the READTHEDOCS  env var is not found.

**Comment by natechols** [comment]
I'm never thrilled by environment variable hacks either, but it seems like the least gross solution in this case.  Will RTD get run in response to a pull request, or only after merging into master?

**Comment by mpkocher** [comment]
Looks good and the rtd appears to work as expected. Thanks
